// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNJ8R-Fh1v1z4LmknIN9XCPPmNCqGJ3YI',
    appId: '1:554691543284:web:3014421f4989cb63e45ea1',
    messagingSenderId: '554691543284',
    projectId: 'internabot',
    authDomain: 'internabot.firebaseapp.com',
    storageBucket: 'internabot.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNU4elZZ4U11OGE0rrA2A6_16ko0eMf0o',
    appId: '1:554691543284:android:db8ecb3d3a107342e45ea1',
    messagingSenderId: '554691543284',
    projectId: 'internabot',
    storageBucket: 'internabot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs000hsfHSbWS1KYhAhI-TlBefLv3IAuU',
    appId: '1:554691543284:ios:d343ac46dc346838e45ea1',
    messagingSenderId: '554691543284',
    projectId: 'internabot',
    storageBucket: 'internabot.firebasestorage.app',
    iosBundleId: 'com.example.internabot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs000hsfHSbWS1KYhAhI-TlBefLv3IAuU',
    appId: '1:554691543284:ios:d343ac46dc346838e45ea1',
    messagingSenderId: '554691543284',
    projectId: 'internabot',
    storageBucket: 'internabot.firebasestorage.app',
    iosBundleId: 'com.example.internabot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNJ8R-Fh1v1z4LmknIN9XCPPmNCqGJ3YI',
    appId: '1:554691543284:web:ca3805f4454b79e8e45ea1',
    messagingSenderId: '554691543284',
    projectId: 'internabot',
    authDomain: 'internabot.firebaseapp.com',
    storageBucket: 'internabot.firebasestorage.app',
  );
}
